language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
# install libjpeg-dev for Pillow to handle JPEGs
sudo: false
addons:
  apt:
    packages:
      - libjpeg-dev
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-xdist
# command to run tests
script: make test PYTESTOPTS="--tb=short -n10"
notifications:
  irc:
    channels:
      - "chat.freenode.net#dosage"
    use_notice: true
    skip_join: true
